<?php
$data = array (
  0 => 
  array (
    'cat_id' => '36',
    'cat_name' => '手机内配',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  1 => 
  array (
    'cat_id' => '38',
    'cat_name' => '平板电脑内配',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  2 => 
  array (
    'cat_id' => '8',
    'cat_name' => '手机配件',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  3 => 
  array (
    'cat_id' => '39',
    'cat_name' => '智能手表配件',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  4 => 
  array (
    'cat_id' => '40',
    'cat_name' => '指尖陀螺',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  5 => 
  array (
    'cat_id' => '37',
    'cat_name' => '平板电脑配件',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  6 => 
  array (
    'cat_id' => '10',
    'cat_name' => 'Ad系列数据线',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  7 => 
  array (
    'cat_id' => '30',
    'cat_name' => '其他系类数据线',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  8 => 
  array (
    'cat_id' => '9',
    'cat_name' => 'iP系列数据线',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '12',
  ),
  9 => 
  array (
    'cat_id' => '33',
    'cat_name' => 'Son系列手机保护壳',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  10 => 
  array (
    'cat_id' => '11',
    'cat_name' => 'iP系列保护壳',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '21',
  ),
  11 => 
  array (
    'cat_id' => '12',
    'cat_name' => 'Sam系列手机保护壳',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '11',
  ),
  12 => 
  array (
    'cat_id' => '35',
    'cat_name' => 'huawei系列手机保护壳',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  13 => 
  array (
    'cat_id' => '15',
    'cat_name' => 'iP系列钢化膜',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  14 => 
  array (
    'cat_id' => '16',
    'cat_name' => 'Sam系类钢化膜',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '22',
  ),
  15 => 
  array (
    'cat_id' => '31',
    'cat_name' => '其他钢化膜',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  16 => 
  array (
    'cat_id' => '17',
    'cat_name' => 'Son系列钢化膜',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  17 => 
  array (
    'cat_id' => '18',
    'cat_name' => '充电宝',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => '2',
  ),
  18 => 
  array (
    'cat_id' => '19',
    'cat_name' => '车载充电器',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  19 => 
  array (
    'cat_id' => '29',
    'cat_name' => 'Son系列电池',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  20 => 
  array (
    'cat_id' => '22',
    'cat_name' => 'Sam系类电池',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => 'iP系列电池',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  22 => 
  array (
    'cat_id' => '23',
    'cat_name' => 'iP系列液晶显示屏',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '15',
  ),
  23 => 
  array (
    'cat_id' => '28',
    'cat_name' => 'Son液晶显示屏',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '10',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => 'Sam系列液晶显示屏',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  25 => 
  array (
    'cat_id' => '4',
    'cat_name' => '钢化玻璃膜',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  26 => 
  array (
    'cat_id' => '1',
    'cat_name' => '电源数据线',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  27 => 
  array (
    'cat_id' => '5',
    'cat_name' => '移动电源',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  28 => 
  array (
    'cat_id' => '2',
    'cat_name' => '手机保护壳',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  29 => 
  array (
    'cat_id' => '34',
    'cat_name' => '111',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  30 => 
  array (
    'cat_id' => '27',
    'cat_name' => 'Son系类手机配件',
    'measure_unit' => '',
    'parent_id' => '36',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '61',
  ),
  31 => 
  array (
    'cat_id' => '7',
    'cat_name' => '液晶显示屏',
    'measure_unit' => '',
    'parent_id' => '36',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  32 => 
  array (
    'cat_id' => '25',
    'cat_name' => 'iP系列手机配件',
    'measure_unit' => '',
    'parent_id' => '36',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '115',
  ),
  33 => 
  array (
    'cat_id' => '26',
    'cat_name' => 'Sam系列手机配件',
    'measure_unit' => '',
    'parent_id' => '36',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  34 => 
  array (
    'cat_id' => '6',
    'cat_name' => '手机电池',
    'measure_unit' => '',
    'parent_id' => '36',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  35 => 
  array (
    'cat_id' => '41',
    'cat_name' => '金属材质',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '43',
  ),
  36 => 
  array (
    'cat_id' => '42',
    'cat_name' => '塑料材质',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '15',
  ),
);
?>